version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Toronto
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: rest-spring-boot-java
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - iararmsantos-network
  rest-spring-boot-java:
    image: iararmsantos/rest-spring-boot-java
    restart: always
    build: ./rest-spring-boot-java
    working_dir: /rest-spring-boot-java
    environment:
      TZ: America/Toronto
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest-spring-boot-java?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - iararmsantos-network
networks:
  iararmsantos-network:
    driver: bridge