name: Continuous Integration with Github Actions

on:
  push:
    branches: 
      -main  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Dockerhub  
      uses: docker/login-action@v2.1.0
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}   
       
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./22_Docker/rest-spring-boot-java
      run: mvn clean package
      
    - name: Docker Compose Build
      working-directory: ./22_Docker
      run: docker compose build

    - name: Push to dockerhub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-spring-boot-java:latest ${{ secrets.DOCKER_USERNAME }}/rest-spring-boot-java:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring-boot-java:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring-boot-java:latest
